### PR TITLE
Migrate Turf GeoJSON usage to GeoJSONObject and JSONValue

### PR DESCRIPTION
**Pull request by 1ec5**
This PR integrates the GeoJSON API changes in mapbox/turf-swift#154 and [Turf v2.0.0-rc.2](https://github.com/mapbox/turf-swift/releases/tag/v2.0.0-rc.2). Most of the changes are in generated code and in tests, though some examples have also changed in minor ways. There is one breaking change on top of the Turf changes: the generic parameter on the `Style.updateGeoJSONSource<T: GeoJSONObject>(withId:geoJSON:)` method has been removed. Instead of passing in the expected GeoJSON object type, you perform pattern matching on the return value using `case let`. (#715)

Depends on mapbox/turf-swift#154.

/cc @mapbox/maps-ios

### CODE REVIEW

File: Sources/MapboxMaps/Style/Style.swift [hunk 1]
```diff
@@ -180,7 +180,7 @@ public class Style {
     ///
     /// - Attention: This method is only effective with sources of `GeoJSONSource`
     /// type, and cannot be used to update other source types.
-    public func updateGeoJSONSource<T: GeoJSONObject>(withId id: String, geoJSON: T) throws {
+    public func updateGeoJSONSource(withId id: String, geoJSON: GeoJSONObject) throws {
```
Comment (macdrevx) [inline Sources/MapboxMaps/Style/Style.swift:183]: Previously, GeoJSONObject could only be Feature or FeatureCollection (or a user-defined conforming type). Let's confirm that it's acceptable for a GeoJSON source's data property to be a geometry that's not wrapped in a feature.

File: Apps/Examples/Examples/All Examples/AnimateLayerExample.swift [hunk 2]
```diff
@@ -108,12 +108,12 @@ public class AnimateLayerExample: UIViewController, ExampleProtocol {
 
             // Identify the new coordinate to animate to, and calculate
             // the bearing between the new coordinate and the following coordinate.
-            var geoJSON = Feature.init(geometry: Geometry.point(Point(coordinate)))
-            geoJSON.properties = ["bearing": coordinate.direction(to: nextCoordinate)]
+            var geoJSON = Feature(geometry: .point(Point(coordinate)))
```
Comment (macdrevx) [inline Apps/Examples/Examples/All Examples/AnimateLayerExample.swift:111]: Something to consider for Turf in the future is introducing a protocol like GEOSwift's GeometryConvertible so that we can avoid the `.point()` wrapper in situations like this. It would make the code look like…

```suggestion
            var geoJSON = Feature(geometry: Point(coordinate))
```

Comment (macdrevx) [reply Apps/Examples/Examples/All Examples/AnimateLayerExample.swift:111]: I suppose we could do the same for GeoJSON as well to avoid having to write out those enum wrappers as often.

File: MapboxMaps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist [hunk 3]
```diff
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+<plist version="1.0">
+<dict>
+	<key>IDEDidComputeMac32BitWarning</key>
+	<true/>
+</dict>
+</plist>
```
Comment (macdrevx) [inline MapboxMaps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist:8]: The entire MapboxMaps.xcworkspace should have been ignored. Let's check the `.gitignore` rules to figure out why it wasn't.

File: Tests/MapboxMapsTests/Foundation/Extensions/Turf/FeatureTests.swift [hunk 4]
```diff
@@ -24,7 +24,7 @@ final class FeatureTests: XCTestCase {
 
         let feature = try XCTUnwrap(Feature(commonFeature))
 
-        guard case .number(.double(2.0)) = feature.identifier else {
+        guard feature.identifier == 2.0 else {
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/Extensions/Turf/FeatureTests.swift:27]: Love this. Very nice.

File: Tests/MapboxMapsTests/Foundation/GeoJSON/FeatureCollectionTests.swift [hunk 5]
```diff
@@ -3,25 +3,20 @@ import CoreLocation
 @testable import MapboxMaps
 
 // Disabling rules against force casting for test file.
-// swiftlint:disable explicit_top_level_acl explicit_acl force_try force_cast
+// swiftlint:disable explicit_top_level_acl explicit_acl force_try
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/GeoJSON/FeatureCollectionTests.swift:6]: None of these should be needed in tests anymore
```suggestion
```

Comment (macdrevx) [reply Tests/MapboxMapsTests/Foundation/GeoJSON/FeatureCollectionTests.swift:6]: Actually, we should just delete this whole file. I don't see why we would need to test Turf in this repo. I'll ticket that separately to make sure I clean up any unused fixtures as well.

File: Tests/MapboxMapsTests/Foundation/Integration Tests/FeatureQueryingTest.swift [hunk 6]
```diff
@@ -79,8 +79,12 @@ internal class FeatureQueryingTest: MapViewIntegrationTestCase {
                        case .success(let filteredFeatures) = filteredFeatures {
 
                         let expectedFilteredFeatures = unfilteredFeatures.filter { queriedFeature in
-                            // `GeometryType(1)` is equal to `GemoetryType`, `point`
-                            return queriedFeature.feature?.geometry.type == .Point
+                            // `GeometryType(1)` is equal to `GeometryType`, `point`
```
Comment (macdrevx) [inline Tests/MapboxMapsTests/Foundation/Integration Tests/FeatureQueryingTest.swift:82]:
```suggestion
```

File: MapboxMaps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (hunk 3 above)
Comment (macdrevx) [reply MapboxMaps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist:8]: looks like we ignore MapboxMaps.xcodeproj but not MapboxMaps.xcworkspace. Feel free to add that to the gitignore if you'd like.

Comment (1ec5) [reply MapboxMaps.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist:8]: I wonder if this happened when I rigged [the navigation SDK’s CocoaPods integration test](https://github.com/mapbox/mapbox-navigation-ios/blob/main/Tests/CocoaPodsTest/PodInstall/Podfile/) to use the map SDK and Turf as development pods. I can remove this file in any case.

File: Sources/MapboxMaps/Style/Style.swift (hunk 1 above)
Comment (1ec5) [reply Sources/MapboxMaps/Style/Style.swift:183]: @galinelle confirmed that a bare geometry is OK. MGLShape was also supported by MGLShapeSource in iOS map SDK v6._x_ and the macOS map SDK, though there’s naturally less you can do to style bare geometries versus features.

File: Apps/Examples/Examples/All Examples/AnimateLayerExample.swift (hunk 2 above)
Comment (1ec5) [reply Apps/Examples/Examples/All Examples/AnimateLayerExample.swift:111]: Good idea! I opened mapbox/turf-swift#158 to track this change. It’d be out of scope for this PR because it would require upgrading to a subsequent version of Turf. In the meantime, I’m also open to writing this as designated initializer shorthand for less redundancy:

```swift
var geoJSON = Feature(geometry: .point(.init(coordinate)))
```

but that might be my Objective-C++ background showing through, maybe too obtuse for an example.

Comment (macdrevx) [reply Apps/Examples/Examples/All Examples/AnimateLayerExample.swift:111]: 😄 I have mixed feelings about type inference with `init`. We use it somewhat inconsistently at the moment. Let's leave this as-is for now, and I'll make a note about coming up with some guidelines around this for the future.

**Review by macdrevx — APPROVED** [review]

**Comment by 1ec5** [comment]
[This build](https://app.circleci.com/pipelines/github/mapbox/mobile-metrics/17561/workflows/d8ccde66-84f2-4eb2-a8b6-26dfe1a36f8a/jobs/33166) is failing, presumably due to #695 so unrelated to this PR:

```
CompileSwift normal arm64 (in target 'MobileMetricsTests' from project 'MobileMetrics')
    cd /Users/distiller/project/ios-maps-carbon/benchmarks
/Users/distiller/project/ios-maps-carbon/MobileMetricsTests/gen/ttrcSymbol/ttrcSymbol_navigation_v4.swift:143:40: error: missing arguments for parameters 'stretchX', 'stretchY' in call
                    try! style.addImage(replacementImage, id: imageName)
                                       ^
/Users/distiller/project/ios-maps-carbon/build/SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Style/Style.swift:706:17: note: 'addImage(_:id:sdf:stretchX:stretchY:content:)' declared here
    public func addImage(_ image: UIImage,
                ^
/Users/distiller/project/ios-maps-carbon/MobileMetricsTests/gen/ttrcSymbol/ttrcSymbol_streets_v11.swift:143:40: error: missing arguments for parameters 'stretchX', 'stretchY' in call
                    try! style.addImage(replacementImage, id: imageName)
                                       ^
/Users/distiller/project/ios-maps-carbon/build/SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Style/Style.swift:706:17: note: 'addImage(_:id:sdf:stretchX:stretchY:content:)' declared here
    public func addImage(_ image: UIImage,
                ^
/Users/distiller/project/ios-maps-carbon/benchmarks/MobileMetricsTests/MapsTestCase.swift:138:52: error: type of expression is ambiguous without more context
            if var layer: SymbolLayer = try? style.layer(withId: id) {
                                        ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/Users/distiller/project/ios-maps-carbon/MobileMetricsTests/gen/ttrcSymbol/ttrcSymbol_satellite_v9.swift:143:40: error: missing arguments for parameters 'stretchX', 'stretchY' in call
                    try! style.addImage(replacementImage, id: imageName)
                                       ^
/Users/distiller/project/ios-maps-carbon/build/SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Style/Style.swift:706:17: note: 'addImage(_:id:sdf:stretchX:stretchY:content:)' declared here
    public func addImage(_ image: UIImage,
                ^
/Users/distiller/project/ios-maps-carbon/MobileMetricsTests/gen/ttrcSymbol/ttrcSymbol_empty_v9.swift:143:40: error: missing arguments for parameters 'stretchX', 'stretchY' in call
                    try! style.addImage(replacementImage, id: imageName)
                                       ^
/Users/distiller/project/ios-maps-carbon/build/SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Style/Style.swift:706:17: note: 'addImage(_:id:sdf:stretchX:stretchY:content:)' declared here
    public func addImage(_ image: UIImage,
                ^
/Users/distiller/project/ios-maps-carbon/MobileMetricsTests/gen/ttrcSymbol/ttrcSymbol_basic_v9.swift:143:40: error: missing arguments for parameters 'stretchX', 'stretchY' in call
                    try! style.addImage(replacementImage, id: imageName)
                                       ^
/Users/distiller/project/ios-maps-carbon/build/SourcePackages/checkouts/mapbox-maps-ios/Sources/MapboxMaps/Style/Style.swift:706:17: note: 'addImage(_:id:sdf:stretchX:stretchY:content:)' declared here
    public func addImage(_ image: UIImage,
                ^
```

#720 proposes making giving these parameters default arguments so that these calls wouldn’t have to be modified.
