### ISSUE TITLE
[Bug] MapboxMaps 11.19.0 fails to build with Xcode 26 beta / Swift 6.2

### ISSUE THREAD

**Issue by BerkeSeker0104** [mapbox/mapbox-maps-ios#2405]
MapboxMaps 11.19.0 fails to compile when using Xcode 26.2 beta (Swift 6.2) on macOS Tahoe.

The pre-built `MapboxCoreMaps.xcframework` `.swiftinterface` files are incompatible with Swift 6.2, causing types defined in MapboxCoreMaps to be unresolvable.

## Environment

- **Xcode:** 26.2 (Build 17C52)
- **macOS:** Tahoe (26.x)
- **Swift:** 6.2
- **MapboxMaps:** 11.19.0
- **MapboxCoreMaps:** 11.19.0
- **MapboxCommon:** 24.19.0
- **Integration:** CocoaPods (via @rnmapbox/maps 10.3.0-rc.0)

## Errors

```swift
error: cannot find type 'CameraState' in scope
error: cannot find type 'CameraOptions' in scope
error: cannot find type 'Heading' in scope
error: cannot find type 'IndoorFloor' in scope
error: cannot find type 'IndoorManager' in scope
error: cannot find type 'IndoorState' in scope
error: no type named 'UIEdgeInsetsCodable' in module 'MapboxCoreMaps'
error: type 'FollowPuckViewportStateOptions' does not conform to protocol 'Decodable'
error: type 'FollowPuckViewportStateOptions' does not conform to protocol 'Hashable'
error: type 'PuckRenderingData' does not conform to protocol 'Equatable'
error: @escaping attribute only applies to function types
Why
Since Xcode 16.4 does not run on macOS Tahoe, developers on macOS Tahoe are completely blocked from building any project that depends on MapboxMaps.

The main branch already references MapboxCoreMaps v11.21.0-rc.1 — would it be possible to publish a release with xcframeworks compiled using Swift 6.2?

**Comment by yashh** [comment]
Also happening on Xcode 26.3

**Comment by battman21** [comment]
This is blocking CarPlay development for our Flutter app. We're on Xcode 26.3 (production, not beta) and cannot upgrade past MapboxMaps 11.11.0 because every version from 11.19+ fails with:

```
Swift Compiler Error: Cannot find type 'Heading' in scope
/ios/Pods/MapboxMaps/Sources/MapboxMaps/Location/AppleLocationProvider.swift:90
```

We've confirmed this on 11.21.1 and 11.22.0-rc.1. The `Heading` struct is defined in MapboxCommon but MapboxMaps can't resolve it during compilation — it's a Swift 6.2 module interface incompatibility in the prebuilt xcframeworks.

This also blocks the Mapbox Navigation SDK v3.x integration since it requires MapboxMaps 11.21+.

Is there any timeline for Xcode 26 / Swift 6.2 compatibility? Are the xcframeworks being rebuilt with the Swift 6.2 compiler? Happy to test pre-release builds.

**Comment by postmechanical** [comment]
This issue persists with Xcode 26.4 and MapboxMaps 11.22.0

**Comment by OdNairy** [comment]
Hey there
It is a CocoaPods specific issue? Could we have a basic repro project? That significantly boost bug fixing process for us

**Comment by postmechanical** [comment]
Swift Package Manager. It's actually C++ interop related.

**Comment by OdNairy** [comment]
The issue should be addressed in the [v11.22.1 release](https://github.com/mapbox/mapbox-maps-ios/releases/tag/v11.22.1) 
Could you confirm that it works for you now? 
It's indeed was related to the Obj-C++

**Comment by yashh** [comment]
@OdNairy Just tried 11.22.1 and it worked for me. Thank you!

**Comment by OdNairy** [comment]
Thank you @yashh for confirmation
I'm closing the ticket for now.
@postmechanical @BerkeSeker0104 @battman21 I would appreciate if you also could confirm the fix
